theme: minima
---
title: "Yo Yo Yo Que Esta Passando Cara de Vainilla"
date: 2022-02-28
---
author: Colby S
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learnin Spanish chicas!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
